// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'FIREBASE_WEB_API_KEY',
    appId: 'FIREBASE_WEB_APP_ID',
    messagingSenderId: '000000000000',
    projectId: 'yourProjectId',
    authDomain: 'yourProjectId.firebaseapp.com',
    storageBucket: 'yourProjectId.firebasestorage.app',
    measurementId: 'A-BCDEF00G1H',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'FIREBASE_ANDROID_API_KEY',
    appId: 'FIREBASE_ANDROID_APP_ID',
    messagingSenderId: '000000000000',
    projectId: 'yourProjectId',
    storageBucket: 'yourProjectId.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'FIREBASE_IOS_API_KEY',
    appId: 'FIREBASE_IOS_APP_ID',
    messagingSenderId: '000000000000',
    projectId: 'yourProjectId',
    storageBucket: 'yourProjectId.firebasestorage.app',
    iosBundleId: 'com.example.yourProjectId',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: 'FIREBASE_IOS_API_KEY',
    appId: 'FIREBASE_IOS_APP_ID',
    messagingSenderId: '000000000000',
    projectId: 'yourProjectId',
    storageBucket: 'yourProjectId.firebasestorage.app',
    iosBundleId: 'com.example.yourProjectId',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: 'FIREBASE_WEB_API_KEY',
    appId: 'FIREBASE_WINDOWS_APP_ID',
    messagingSenderId: '000000000000',
    projectId: 'yourProjectId',
    authDomain: 'yourProjectId.firebaseapp.com',
    storageBucket: 'yourProjectId.firebasestorage.app',
    measurementId: 'A-BCDEF00G1H',
  );
}